version: '3.8'
services:
  app:
    build: .
    image: python-test-instagram-project
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge